# Generated by Django 4.1.1 on 2022-09-15 09:49

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("balance", models.BigIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("time_datetime", models.DateTimeField(blank=True, null=True)),
                (
                    "perform_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tasdiqlangan vaqti:"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Yaratilgan vaqti:"
                    ),
                ),
                ("cancel_time", models.DateTimeField(blank=True, null=True)),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Tranzaksiya sababi (izoh)",
                    ),
                ),
                (
                    "error",
                    models.TextField(blank=True, default="Aniqlanmadi!", null=True),
                ),
                (
                    "state",
                    models.IntegerField(
                        choices=[
                            (0, "Не существует"),
                            (1, "Создан"),
                            (2, "Оплачен"),
                            (-1, "Отменен"),
                            (-2, "Отменена после завершения"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "credit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="billing.agentbalance",
                    ),
                ),
                (
                    "debit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
