# Generated by Django 4.1.1 on 2022-09-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="time_millisecond",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name="API kelgan vaqt (format:millisecond)",
            ),
        ),
    ]
