# Generated by Django 4.1.1 on 2022-09-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_transaction_time_millisecond"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentbalance",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="agentbalance",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
