# Generated by Django 4.1 on 2022-08-30 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_title', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ismi')),
                ('sur_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Familiyasi')),
                ('mid_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Otasining ismi')),
                ('username', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Elektron pochta manzili*')),
                ('pinfl', models.CharField(blank=True, max_length=255, null=True, verbose_name='Shahsiy identifikatsiya raqami')),
                ('stir', models.CharField(blank=True, max_length=255, null=True, verbose_name='INN')),
                ('passport', models.CharField(blank=True, max_length=24, null=True, verbose_name='Pasport')),
                ('phone', models.CharField(blank=True, max_length=128, null=True, verbose_name='Telefon raqami')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sanasi")),
                ('gd', models.CharField(blank=True, max_length=255, null=True, verbose_name='Jinsi')),
                ('per_adr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Manzili')),
                ('birth_place', models.CharField(blank=True, max_length=255, null=True, verbose_name="Tug'ilgan joyi")),
                ('birth_country', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tugilgan mamlakati')),
                ('citizenship', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fuqoroligi')),
                ('nationality', models.CharField(blank=True, max_length=255, null=True, verbose_name='Millati')),
                ('pport_issue_place', models.CharField(blank=True, max_length=255, null=True, verbose_name='Pasport berilgan joy')),
                ('pport_issue_date', models.DateField(blank=True, null=True, verbose_name='Pasport berilgan sani')),
                ('pport_expr_date', models.DateField(blank=True, null=True, verbose_name='Pasport amal qilish muddati')),
                ('legal_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Yuridik shahsning nomi')),
                ('legal_stir', models.CharField(blank=True, max_length=255, null=True, verbose_name='Yuridik shahsning INN raqami')),
                ('legal_props', models.CharField(blank=True, max_length=255, null=True, verbose_name='Rekvizitlari')),
                ('status', models.IntegerField(choices=[(1, 'New'), (2, 'Active'), (3, 'Deleted')], default=1)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('activated_date', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
