# Generated by Django 4.1 on 2022-09-02 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birth_country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='birth_place',
        ),
        migrations.RemoveField(
            model_name='user',
            name='citizenship',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gd',
        ),
        migrations.RemoveField(
            model_name='user',
            name='legal_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='legal_props',
        ),
        migrations.RemoveField(
            model_name='user',
            name='legal_stir',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pinfl',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pport_expr_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pport_issue_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pport_issue_place',
        ),
    ]
