# Generated by Django 4.1 on 2022-09-03 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
