# Generated by Django 4.1 on 2022-09-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=21, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
