# Generated by Django 4.1 on 2022-09-05 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='passport',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='stir',
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='user',
            name='per_adr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address'),
        ),
    ]
