# Generated by Django 4.1 on 2022-09-06 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
