# Generated by Django 4.1 on 2022-09-06 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_delete_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
    ]
