# Generated by Django 4.1 on 2022-10-11 06:24

import api.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_article_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='company',
            field=models.CharField(default='0000000', max_length=100),
        ),
        migrations.AddField(
            model_name='article',
            name='endDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='flight',
            field=models.BooleanField(default=False, verbose_name='Flight included'),
        ),
        migrations.AddField(
            model_name='article',
            name='guide',
            field=models.BooleanField(default=False, verbose_name='Guide included'),
        ),
        migrations.AddField(
            model_name='article',
            name='hotel',
            field=models.BooleanField(default=False, verbose_name='Hotel included'),
        ),
        migrations.AddField(
            model_name='article',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_path),
        ),
        migrations.AddField(
            model_name='article',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_path),
        ),
        migrations.AddField(
            model_name='article',
            name='insurance',
            field=models.BooleanField(default=False, verbose_name='Insurance included'),
        ),
        migrations.AddField(
            model_name='article',
            name='price_over_18',
            field=models.DecimalField(decimal_places=0, default=50, max_digits=20, verbose_name='Price for over 18'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='price_under_18',
            field=models.DecimalField(decimal_places=0, default=50, max_digits=20, verbose_name='Price for under 18'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='quantity',
            field=models.DecimalField(decimal_places=0, default='1', max_digits=20, verbose_name='Quantity for under 3'),
        ),
        migrations.AddField(
            model_name='article',
            name='quantity2',
            field=models.DecimalField(decimal_places=0, default='1', max_digits=20, verbose_name='Quantity for under 18'),
        ),
        migrations.AddField(
            model_name='article',
            name='quantity3',
            field=models.DecimalField(decimal_places=0, default='1', max_digits=20, verbose_name='Quantity for over 18'),
        ),
        migrations.AddField(
            model_name='article',
            name='startDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'Active'), (3, 'Deleted')], default=1),
        ),
        migrations.AlterField(
            model_name='article',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=20, verbose_name='Price for under 3'),
        ),
    ]
