class PaycomStatus:
    """Transaction timeout 12 hours"""

    TIMEOUT = 43200000

    STATE_CREATED = 1
    STATE_COMPLETED = 2
    STATE_CANCELLED = -1
    STATE_CANCELLED_AFTER_COMPLETE = -2

    REASON_RECEIVERS_NOT_FOUND = 1
    REASON_PROCESSING_EXECUTION_FAILED = 2
    REASON_EXECUTION_FAILED = 3
    REASON_CANCELLED_BY_TIMEOUT = 4
    REASON_FUND_RETURNED = 5
    REASON_UNKNOWN = 10

    TRANSACTION_CAN_NOT_PERFORM = -31008
    TRANSACTION_CAN_NOT_CANCEL = -31007
    TRANSACTION_INVALID_AMOUNT = -31001
    TRANSACTION_NOT_FOUND = -31003
    TRANSACTION_INVALID_ACCOUNT = -31050
